CREATE TABLE role (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(45) NOT NULL
);

ALTER TABLE role ADD CONSTRAINT role_name_uniq UNIQUE (name);

INSERT INTO role (id, name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO role (id, name) VALUES (2, 'ROLE_USER');


CREATE TABLE user (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(45) NOT NULL,
  password varchar(200) NOT NULL,
  email varchar(200) NOT NULL,
  nonlocked tinyint NOT NULL,
  nonexpired tinyint NOT NULL,
  credentialsnonexpired tinyint NOT NULL,
  enabled tinyint NOT NULL
);

ALTER TABLE user ADD CONSTRAINT user_email_uniq UNIQUE (email);
ALTER TABLE user ADD CONSTRAINT user_username_uniq UNIQUE (username);

INSERT INTO user (id, username, password, email, nonlocked, nonexpired, credentialsnonexpired, enabled) 
VALUES (1, 'himanshu', '$2a$10$Dda1sOv8IvLptY95yobXV.N4jzHPKlEF/av8PZccnclO96vkYwHBu', 'abc@test.com', 1, 1, 1, 1);

CREATE TABLE user_role_mapping (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userid int NOT NULL,
  roleid int NOT NULL
);

ALTER TABLE user_role_mapping ADD FOREIGN KEY (roleid) REFERENCES role (id);
ALTER TABLE user_role_mapping ADD FOREIGN KEY (userid) REFERENCES user (id);

INSERT INTO user_role_mapping (id, userid, roleid) VALUES (1, 1, 2);
