CREATE TABLE customer (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(45) NOT NULL,
  email varchar(200) NOT NULL,
  city varchar(200) NOT NULL,
  country varchar(200) NOT NULL
);

ALTER TABLE customer ADD CONSTRAINT customer_email_uniq UNIQUE (email);
ALTER TABLE customer ADD CONSTRAINT customer_username_uniq UNIQUE (username);

insert into customer (id, username, email, city, country) values (1, 'himanshu', 'test@abc.com', 'DEL', 'IN');

CREATE TABLE items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(45) NOT NULL,
  description varchar(45) NOT NULL,
  inventory INT NOT NULL,
  price NUMERIC(10,2) NOT NULL
);

insert into items (id, name, description, inventory, price) values (1, 'Keyboard', 'Cliche keyboards', 10000, 9.99);
insert into items (id, name, description, inventory, price) values (2, 'Monitor', 'LED screens', 5000, 29.99);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id int NOT NULL,
  price NUMERIC(10,2) NOT NULL
);

ALTER TABLE orders ADD FOREIGN KEY (customer_id) REFERENCES customer (id);

insert into orders (id, customer_id, price) values (1, 1, 19.99);

CREATE TABLE order_item_mapping (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id int NOT NULL,
  items int NOT NULL,
  item_count int NOT NULL
);

ALTER TABLE order_item_mapping ADD FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_item_mapping ADD FOREIGN KEY (items) REFERENCES items (id);